prod: &default
  secret_key: 48716746efd74c80b72175f17e40224f

  client:
    port: 8000
  http:
    port: 8001
    allow_origins:
      - http://localhost
    allow_headers:
      - Authorization
      - X-Requested-With
      - X-Client-Version
      - Origin
      - Content-Type
      - WithCredentials
    allow_methods:
      - PUT
      - PATCH
      - GET
      - POST
      - DELETE
      - OPTIONS
    allow_wildcard: true
    allow_credentials: true
    expose_headers:
      - Content-Length
    max_age: 12h
  db:
    driver: sqlite3
    dsn: database.sql
dev: 
  <<: *default